### PR TITLE
debug: Implement bprintf() serial debugging function

### LINKED ISSUE #12: Support serial port debug messages
In the event a display is not attached or something fails very early, it may be useful to support printing debug output via serial port. There is a compatible serial implementation that can be used here: https://github.com/mborgerson/xqemu-kernel/blob/master/src/drivers/serial/serial.c

### PR DESCRIPTION
**Pull request by binarymaster**
Fixes #12.

### CODE REVIEW

File: drivers/pci/pci.c [hunk 1]
```diff
@@ -206,6 +207,30 @@ void LpcSetSerialState(int enable)
...
+}
+
+void bprintf(const char *fmt, ...)
+{
+	va_list args;
+	char buf[256] = {0};
+	int i;
+
+	va_start(args, fmt);
+	vsprintf(&buf, fmt, args);
```
Comment (mborgerson) [inline drivers/pci/pci.c]: Any formatted string of length greater than 255 will overflow buffer. Unfortunately, it looks like we don't have a 'vsnprintf' implementation that would allow us to specify the size of the buffer. It's probably ok for now, but something to watch out for and which should likely be fixed in the future.

File: drivers/pci/pci.c [hunk 2]
```diff
@@ -206,6 +207,30 @@ void LpcSetSerialState(int enable)
 	LpcWriteRegister(0x30, enable ? 0x01 : 0x00);
 }
 
+int serial_putchar(int ch)
+{
+	/* Wait for THRE (bit 5) to be high */
+	while ((IoInputByte(SERIAL_PORT + SERIAL_LSR) & (1 << 5)) == 0);
+	IoOutputByte(SERIAL_PORT + SERIAL_THR, ch);
+	return ch;
```
Comment (mborgerson) [inline drivers/pci/pci.c]: If outputting strings to a serial terminal, you'll likely want to print carriage returns (`\r`) whenever a linefeed character (`\n`) is emitted. Without the carriage return, the terminal may move to the next line and continue at the same place as before. Recommend simply adding a recursive call here.

Comment (binarymaster) [reply drivers/pci/pci.c]: Improved.

**Comment by mborgerson** [comment]
Thanks!
